// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js/vue';
import type { ResponsiveBones } from 'boneyard-js';

import _dashboard_layout from './dashboard-layout.bones.json';
import _public_layout from './public-layout.bones.json';

registerBones({
  'dashboard-layout': _dashboard_layout as unknown as ResponsiveBones,
  'public-layout': _public_layout as unknown as ResponsiveBones,
});
